// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALilgVPufhEbx6_QS29tsQr4HQIXpjX1Y',
    appId: '1:255568203751:web:db6252e424aa6d232e7742',
    messagingSenderId: '255568203751',
    projectId: 'licenta-4bfa8',
    authDomain: 'licenta-4bfa8.firebaseapp.com',
    storageBucket: 'licenta-4bfa8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoKdcwXNJbS85edZHpvdiuYcVX3hsmk1Q',
    appId: '1:255568203751:android:eda264a3164e95de2e7742',
    messagingSenderId: '255568203751',
    projectId: 'licenta-4bfa8',
    storageBucket: 'licenta-4bfa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoiIJj8q2M5O-GYnxzlY1jlOC9hbJ8ijE',
    appId: '1:255568203751:ios:a3d63018aeace62f2e7742',
    messagingSenderId: '255568203751',
    projectId: 'licenta-4bfa8',
    storageBucket: 'licenta-4bfa8.appspot.com',
    androidClientId: '255568203751-egj8eu2l3q31au9hbmono9lv3jncerku.apps.googleusercontent.com',
    iosClientId: '255568203751-578hmf1tet266csi1vnqvdh36nnrrb5j.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.licentamain',
  );
}
